export type ChoiceKey = "A" | "B" | "C" | "D";

export type TopicId =
  | "objekt"
  | "premenne"
  | "transformacia"
  | "univariacna"
  | "reliabilita"
  | "korelacny"
  | "komparacny";

export type PsychologyQuestion = {
  id: string;
  topic: TopicId;
  source: string;
  prompt: string;
  choices: Array<{ key: ChoiceKey; text: string }>;
  correct: ChoiceKey;
  explanation: string;
  fromExampleTest?: boolean;
};

export const topics: Array<{
  id: TopicId;
  label: string;
  note: string;
  presentation: string;
}> = [
  {
    id: "objekt",
    label: "Objekt a výber",
    note: "Populácia, reprezentativita a typy výberu",
    presentation: "1. Objekt výskumu",
  },
  {
    id: "premenne",
    label: "Premenné a PSPP",
    note: "Úrovne merania, syntax a práca s dátovým súborom",
    presentation: "2. Predmet výskumu + 3. PSPP + 4. Tvorba dátového súboru",
  },
  {
    id: "transformacia",
    label: "Transformácia dát",
    note: "Rekódovanie, sumačné indexy a syntax",
    presentation: "5. Transformácia dát",
  },
  {
    id: "univariacna",
    label: "Univariačná analýza",
    note: "Modus, medián, distribúcia a grafy",
    presentation: "6. Univariačná analýza",
  },
  {
    id: "reliabilita",
    label: "Reliabilita",
    note: "Test-retest, split half a Cronbachovo alfa",
    presentation: "7. Reliabilita psychologického merania",
  },
  {
    id: "korelacny",
    label: "Korelačný výskum",
    note: "Kontingencia, korelácie, eta a hypotézy",
    presentation: "8. Korelačný psychologický výskum",
  },
  {
    id: "komparacny",
    label: "Komparačný výskum",
    note: "Rozdiely, effect size a výber testu",
    presentation: "9. Komparačný psychologický výskum",
  },
];

const keys: ChoiceKey[] = ["A", "B", "C", "D"];

function q(
  id: string,
  topic: TopicId,
  source: string,
  prompt: string,
  answers: [string, string, string, string],
  correct: ChoiceKey,
  explanation: string,
  fromExampleTest = false,
): PsychologyQuestion {
  return {
    id,
    topic,
    source,
    prompt,
    choices: answers.map((text, index) => ({ key: keys[index], text })),
    correct,
    explanation,
    fromExampleTest,
  };
}

export const psychologyQuestions: PsychologyQuestion[] = [
  q(
    "obj-01",
    "objekt",
    "1. Objekt výskumu",
    "Objekt výskumu odpovedá predovšetkým na otázku:",
    ["O kom alebo o čom výskum je?", "Aký graf použijeme?", "Aké je p?", "Ako vypočítame priemer?"],
    "A",
    "Objekt vymedzuje skúmanú populáciu alebo populácie.",
  ),
  q(
    "obj-02",
    "objekt",
    "1. Objekt výskumu",
    "Populácia (základný súbor) vo výskume je:",
    [
      "iba skupina participantov, ktorí odpovedali",
      "presne definovaný súbor, ku ktorému chceme vzťahovať závery",
      "tabuľka výstupov z PSPP",
      "iba skupina s normálnou distribúciou",
    ],
    "B",
    "Výskumné otázky a hypotézy sa formulujú o populácii; výber ju má zastupovať.",
  ),
  q(
    "obj-03",
    "objekt",
    "1. Objekt výskumu",
    "V dátovom súbore PSPP predstavuje jednu štatistickú jednotku spravidla:",
    ["jeden riadok", "jeden stĺpec", "jedno syntaxové okno", "jeden graf"],
    "A",
    "Riadok obsahuje údaje jedného participanta; stĺpec predstavuje premennú.",
  ),
  q(
    "obj-04",
    "objekt",
    "1. Objekt výskumu",
    "Reprezentativita výberového súboru vyjadruje:",
    [
      "koľko grafov vytvoríme",
      "mieru, v akej možno zistenia preniesť na cieľovú populáciu",
      "iba celkový počet respondentov",
      "počet chýbajúcich odpovedí",
    ],
    "B",
    "Veľký súbor sám osebe nezaručuje reprezentativitu.",
  ),
  q(
    "obj-05",
    "objekt",
    "1. Objekt výskumu",
    "Pri systematickom výbere označuje pomer N/n:",
    ["výberový krok F", "Cronbachovo alfa", "koeficient eta", "medzikvartilové rozpätie"],
    "A",
    "Po náhodnom určení prvého prípadu vyberáme ďalších podľa kroku F = N/n.",
  ),
  q(
    "obj-06",
    "objekt",
    "1. Objekt výskumu",
    "Výber, pri ktorom má súbor kopírovať podiel mužov a žien v populácii, je:",
    ["skupinový", "snehová guľa", "kvótny", "náhodilý"],
    "C",
    "Kvótny výber pracuje s vopred určenými kvótnymi znakmi, napríklad pohlavím.",
  ),
  q(
    "obj-07",
    "objekt",
    "1. Objekt výskumu",
    "Výskumník rozdelí zamestnancov podľa praxe a z každej skupiny náhodne vyberie ľudí. Ide o výber:",
    ["stratifikovaný", "skupinový", "náhodilý", "časový a miestny"],
    "A",
    "Pri stratifikovanom výbere sa najskôr vytvoria subpopulácie a z každej sa náhodne vyberá.",
  ),
  q(
    "obj-08",
    "objekt",
    "1. Objekt výskumu",
    "Výskumník náhodne vyberie päť liečební a osloví všetkých klientov vo vybraných liečebniach. Ide o:",
    ["kvótny výber", "skupinový výber", "systematický výber", "snehovú guľu"],
    "B",
    "Pri skupinovom výbere sa vyberajú celé prirodzené skupiny a ich členovia.",
  ),
  q(
    "obj-09",
    "objekt",
    "1. Objekt výskumu",
    "Oslovený užívateľ látky poskytne kontakty na ďalších užívateľov. Tento postup je:",
    ["jednoduchý náhodný výber", "stratifikovaný výber", "metóda snehovej gule", "kvótny výber"],
    "C",
    "Metóda snehovej gule získava nové kontakty prostredníctvom už oslovených ľudí.",
  ),
  q(
    "obj-10",
    "objekt",
    "01 Objekt výskumu (Word poznámky)",
    "Výberová chyba, ktorá vyjadruje rozdiel medzi populačnou a z výberu odhadnutou charakteristikou, sa skladá z:",
    [
      "validity a reliability",
      "mediánu a priemeru",
      "náhodnej a systematickej chyby",
      "percenta a validného percenta",
    ],
    "C",
    "Systematická chyba súvisí napríklad so spôsobom výberu; náhodná chyba vzniká výberovou náhodou.",
  ),
  q(
    "obj-11",
    "objekt",
    "01 Objekt výskumu (Word poznámky)",
    "Participantky sú do výskumu zaradené iba vtedy, ak prekonali rakovinu prsníka a od liečby uplynul aspoň rok. Ide o:",
    ["systematický výber", "jednoduchý náhodný výber", "kvótny výber", "zámerný výber"],
    "D",
    "Pri zámernom výbere sú prípady zaradené podľa vopred stanovených kritérií.",
  ),
  q(
    "var-01",
    "premenne",
    "Príkladový test + 2. Predmet výskumu",
    "Ktoré z nasledujúcich tvrdení o premennej je pravdivé?",
    [
      "Nadobúda vždy len jednu hodnotu.",
      "V jednom výskume môžeme skúmať len jednu premennú.",
      "Je vyjadrením predmetu výskumu a môže nadobúdať viac hodnôt.",
      "V dátovom súbore je každý riadok jednou premennou.",
    ],
    "C",
    "Premenná je merateľné vyjadrenie predmetu výskumu a jej podstatou je variabilita hodnôt.",
    true,
  ),
  q(
    "var-02",
    "premenne",
    "2. Predmet výskumu",
    "Proces prevodu teoretickej, priamo nemerateľnej premennej na empiricky merateľnú sa nazýva:",
    ["operacionalizácia", "randomizácia", "kontingencia", "generalizácia"],
    "A",
    "Napríklad depresiu operacionalizujeme skóre v príslušnom dotazníku.",
  ),
  q(
    "var-03",
    "premenne",
    "2. Predmet výskumu",
    "Ktorá dvojica správne spája latentnú a manifestnú premennú?",
    [
      "inteligencia - IQ skóre",
      "vek - prosociálnosť",
      "pohlavie - depresia",
      "graf - dotazník",
    ],
    "A",
    "Latentný konštrukt inteligencia sa empiricky prejaví napríklad IQ skóre.",
  ),
  q(
    "var-04",
    "premenne",
    "Príkladový test + 2. Predmet výskumu",
    "Ktoré tvrdenie o kvalitatívnej premennej je nepravdivé?",
    [
      "Varianty môžeme zaradiť do tried alebo kategórií.",
      "Na kvalitatívnu premennú sa pýtame otázkou „ako?“.",
      "Úroveň kvalitatívnej premennej najčastejšie charakterizujeme priemerom.",
      "Kvalitatívne premenné možno zaradiť do kategórie A.",
    ],
    "C",
    "Kvalitatívne premenné bežne opisujeme početnosťami, percentami a modusom, nie priemerom.",
    true,
  ),
  q(
    "var-05",
    "premenne",
    "Príkladový test + 2. Predmet výskumu",
    "Ktorá z premenných má kardinálnu škálu?",
    [
      "vek v kategóriách 15-18, 18-20 a 20-22 rokov",
      "váha: podváha, optimálna váha, nadváha, obezita",
      "počet bodov z cvičenia: 0 až 10 bodov",
      "čas venovaný príprave: 1 hodina, 2 hodiny, 3 a viac hodín",
    ],
    "C",
    "Pri počte bodov vieme číselne vyjadriť rozdiel medzi hodnotami.",
    true,
  ),
  q(
    "var-06",
    "premenne",
    "2. Predmet výskumu",
    "Premenná „farba očí“ je na úrovni:",
    ["nominálnej", "ordinálnej", "intervalovej", "pomerovej"],
    "A",
    "Kategórie farby očí nemajú prirodzené poradie.",
  ),
  q(
    "var-07",
    "premenne",
    "2. Predmet výskumu",
    "Premenná „spokojnosť: veľmi nespokojný až veľmi spokojný“ je najlepšie označená ako:",
    ["nominálna", "ordinálna", "dichotomická", "textová bez úrovne"],
    "B",
    "Varianty vieme zoradiť, ale rozdiel medzi susednými možnosťami nepoznáme číselne.",
  ),
  q(
    "var-08",
    "premenne",
    "Príkladový test + 3. Štatistický program PSPP",
    "Premenná má label „Stratégie zvládania záťaže“. Ktorý počítačový názov je v PSPP najvhodnejší?",
    ["1_zataz", "strategie_zvladania", "stratégiezvládania", "strategie zvladania"],
    "B",
    "Počítačový názov nesmie začínať číslicou, obsahovať diakritiku ani medzeru.",
    true,
  ),
  q(
    "var-09",
    "premenne",
    "2. Predmet výskumu + 3. PSPP",
    "Označenie premennej (label) v PSPP:",
    [
      "nesmie obsahovať medzeru ani diakritiku",
      "môže byť čitateľný text s medzerami a diakritikou",
      "musí byť iba číslo",
      "určuje správnu odpoveď v teste",
    ],
    "B",
    "Obmedzenia platia pre počítačový názov, nie pre label určený na čítanie vo výstupoch.",
  ),
  q(
    "var-10",
    "premenne",
    "3. Štatistický program PSPP",
    "V pohľade Data view v PSPP platí:",
    ["riadok = premenná", "riadok = participant", "stĺpec = graf", "stĺpec = hypotéza"],
    "B",
    "Data view organizuje participantov v riadkoch a premenné v stĺpcoch.",
  ),
  q(
    "var-11",
    "premenne",
    "3. Štatistický program PSPP",
    "Stĺpec Measure v PSPP vyjadruje:",
    ["typ úrovne merania premennej", "meno výskumníka", "počet hypotéz", "farbu grafu"],
    "A",
    "V Measure nastavujeme napríklad Nominal, Ordinal alebo Scale.",
  ),
  q(
    "var-12",
    "premenne",
    "03 PSPP editor dát (Word poznámky)",
    "Stĺpec Missing Values v PSPP slúži na:",
    [
      "zadanie názvu premennej",
      "definovanie hodnôt, ktoré sa nemajú zaradiť do analýzy ako platné údaje",
      "vytvorenie grafu",
      "výpočet Cronbachovho alfa",
    ],
    "B",
    "Užívateľskú chýbajúcu hodnotu môžeme určiť napríklad pre kategóriu, ktorú nechceme analyzovať.",
  ),
  q(
    "var-13",
    "premenne",
    "04 Tvorba dátového súboru (Word poznámky)",
    "Ktorým syntaxovým príkazom v PSPP podľa poznámok vytvoríme premenné nového dátového súboru?",
    ["DATA LIST", "SPLIT FILE", "RELIABILITY", "CROSSTABS"],
    "A",
    "Príkaz DATA LIST uvádza počítačové názvy premenných a po častiach BEGIN DATA. a END DATA. vytvorí štruktúru súboru.",
  ),
  q(
    "var-14",
    "premenne",
    "04 Tvorba dátového súboru (Word poznámky)",
    "Príkaz VARIABLE LABEL slúži v PSPP na:",
    [
      "vytvorenie priemerných poradí",
      "rozdelenie dát podľa pohlavia",
      "testovanie nulovej hypotézy",
      "priradenie čitateľného označenia premennej k jej počítačovému názvu",
    ],
    "D",
    "Napríklad k názvu `Pohl` priradíme label `Pohlavie`; label môže byť zrozumiteľný text.",
  ),
  q(
    "var-15",
    "premenne",
    "04 Tvorba dátového súboru (Word poznámky)",
    "Príkaz VALUE LABELS používame v PSPP na:",
    [
      "premenovanie súboru",
      "výpočet mediánu",
      "označenie významu jednotlivých kódovaných hodnôt, napríklad 1 = muž a 2 = žena",
      "výber iba platných participantov",
    ],
    "C",
    "Value labels vysvetľujú číselné kódy kategórií alebo odpoveďových variantov.",
  ),
  q(
    "var-16",
    "premenne",
    "04 Tvorba dátového súboru (Word poznámky)",
    "Ak chceme hromadne nastaviť premenné ako NOMINAL, ORDINAL alebo SCALE, v syntaxe použijeme:",
    ["BEGIN DATA", "VARIABLE LEVEL", "RANK CASES", "SPLIT FILE"],
    "B",
    "Príkaz VARIABLE LEVEL nastavuje úroveň merania premenných v stĺpci Measure.",
  ),
  q(
    "trn-01",
    "transformacia",
    "Príkladový test + 5. Transformácia dát",
    "Ak chceme vytvoriť nový stĺpec „vekové kategórie“ a zachovať pôvodný vek, použijeme:",
    ["Recode into Same Variables", "Recode into Different Variables", "Rank Cases", "Split File"],
    "B",
    "Recode into Different Variables vytvorí novú premennú a pôvodnú ponechá.",
    true,
  ),
  q(
    "trn-02",
    "transformacia",
    "5. Transformácia dát",
    "Pri reverznom rekódovaní sedembodovej položky sa hodnota 2 zmení na:",
    ["2", "4", "6", "7"],
    "C",
    "Pri škále 1 až 7 sa dvojice obracajú: 1-7, 2-6, 3-5 a 4-4.",
  ),
  q(
    "trn-03",
    "transformacia",
    "5. Transformácia dát",
    "Sumačný index viacerých položiek vytvárame v PSPP najmä príkazom:",
    ["Compute", "Split File", "Crosstabs", "Rank Cases"],
    "A",
    "Compute umožní sčítať položky do novej súhrnnej premennej.",
  ),
  q(
    "trn-04",
    "transformacia",
    "Príkladový test + 5. Transformácia dát",
    "Ak chceme v PSPP najprv vygenerovať syntax príkazu na rekódovanie škály, v dialógovom boxe zvolíme:",
    ["Change", "Rename", "Paste", "Ok"],
    "C",
    "Paste vloží príkaz do syntaxového okna; potom ho možno uložiť a manuálne spustiť.",
    true,
  ),
  q(
    "trn-05",
    "transformacia",
    "5. Transformácia dát",
    "Aby PSPP vykonal príkazy zo syntaxového okna, musí byť otvorený aj:",
    ["prepojený dátový súbor", "webový prehliadač", "koláčový graf", "iba výstup v PDF"],
    "A",
    "Syntax bez otvoreného dátového súboru nemá nad čím príkazy vykonať.",
  ),
  q(
    "trn-06",
    "transformacia",
    "5. Transformácia dát",
    "Recode into Same Variables znamená:",
    [
      "transformovať hodnoty v pôvodnej premennej",
      "vypočítať koreláciu",
      "rozdeliť súbor podľa skupín",
      "zistiť reliabilitu",
    ],
    "A",
    "Tento postup mení hodnoty pôvodného stĺpca, napríklad pri rekódovaní položiek.",
  ),
  q(
    "uni-01",
    "univariacna",
    "Príkladový test + 6. Univariačná analýza",
    "Vyjadrením podielu odpovedí z celkového počtu reálne získaných odpovedí sú:",
    ["percentá", "validné percentá", "kumulatívne percentá", "početnosti"],
    "B",
    "Valid percent nezahŕňa chýbajúce odpovede do menovateľa.",
    true,
  ),
  q(
    "uni-02",
    "univariacna",
    "Príkladový test + 6. Univariačná analýza",
    "Medzikvartilové rozpätie je:",
    [
      "rozdiel medzi tretím a prvým kvartilom",
      "čiara v krabičkovom grafe označujúca medián",
      "vzdialenosť priemeru od minima",
      "rozdiel medzi 75. a 25. percentilom počítaný iba pri normálnych dátach",
    ],
    "A",
    "IQR = Q3 - Q1; ide zároveň o rozdiel 75. a 25. percentilu bez požiadavky normality.",
    true,
  ),
  q(
    "uni-03",
    "univariacna",
    "Príkladový test + 6. Univariačná analýza",
    "Koeficient Skw = -2,21 naznačuje, že distribúcia premennej je:",
    ["symetrická", "menej špicatá ako gaussovská", "zľava zošikmená", "sprava zošikmená"],
    "C",
    "Záporný koeficient šikmosti znamená ľavostrannú (zápornú) šikmosť.",
    true,
  ),
  q(
    "uni-04",
    "univariacna",
    "Príkladový test + 6. Univariačná analýza",
    "Ktoré tvrdenie o modálnej hodnote je nepravdivé?",
    [
      "V stĺpcovom grafe ju znázorňuje najnižší stĺpec.",
      "Modus je najčastejšie sa vyskytujúca hodnota.",
      "Možno ju zistiť z frekvenčnej tabuľky.",
      "Súbor môže mať viac modálnych hodnôt.",
    ],
    "A",
    "Modálnu hodnotu v grafe ukazuje najvyšší, nie najnižší stĺpec.",
    true,
  ),
  q(
    "uni-05",
    "univariacna",
    "Príkladový test + 6. Univariačná analýza",
    "V rámci univariačnej analýzy premennej z kategórie A počítame:",
    ["hodnoty kvartilov", "priemerné hodnoty", "modálne hodnoty", "empirické minimum"],
    "C",
    "Pre nominálne a málopočetné ordinálne premenné používame početnosti, percentá a modus.",
    true,
  ),
  q(
    "uni-06",
    "univariacna",
    "Príkladový test + 6. Univariačná analýza",
    "Realizujeme univariačnú analýzu negaussovskej premennej kategórie B. Túto premennú nemôžeme znázorniť prostredníctvom:",
    ["koláčového grafu", "krabičkového grafu", "korelačného grafu", "histogramu"],
    "C",
    "Korelačný graf zobrazuje vzťah dvoch premenných, preto nepatrí do univariačnej analýzy.",
    true,
  ),
  q(
    "uni-07",
    "univariacna",
    "6. Univariačná analýza",
    "Premenné kategórie B zahŕňajú:",
    [
      "iba nominálne premenné",
      "ordinálne viacpočetné a kardinálne negaussovské premenné",
      "iba kardinálne gaussovské premenné",
      "iba dichotomické premenné",
    ],
    "B",
    "Pre kategóriu B pridávame medián, kvartily, boxplot, šikmosť a špicatosť.",
  ),
  q(
    "uni-08",
    "univariacna",
    "6. Univariačná analýza",
    "Medián uprednostňujeme pred priemerom najmä pri:",
    [
      "ordinálnych a kardinálnych negaussovských premenných",
      "výlučne nominálnych premenných",
      "všetkých gaussovských premenných bez výnimky",
      "počítaní Cramerovho V",
    ],
    "A",
    "Medián je odolnejší voči extrémnym hodnotám a vhodný pre kategóriu B.",
  ),
  q(
    "uni-09",
    "univariacna",
    "6. Univariačná analýza",
    "Krabičkový graf znázorňuje okrem iného:",
    ["medián a prvý i tretí kvartil", "iba priemer", "iba modus", "Pearsonovo r"],
    "A",
    "Boxplot zobrazuje minimum, maximum, medián, Q1, Q3 a vybočujúce hodnoty.",
  ),
  q(
    "uni-10",
    "univariacna",
    "Príkladový test + 6. Univariačná analýza",
    "Za extrémne hodnoty v krabičkovom grafe považujeme podľa prezentácie hodnoty vzdialené viac ako:",
    ["0,5-násobok IQR", "1,5-násobok IQR", "3-násobok priemeru", "jeden medián"],
    "B",
    "Prezentácia používa hranicu 1,5-násobku medzikvartilového rozpätia.",
    true,
  ),
  q(
    "uni-11",
    "univariacna",
    "6. Univariačná analýza",
    "Kladná hodnota koeficientu špicatosti (Kurt) označuje distribúciu:",
    ["leptokurtickú", "platykurtickú", "nominálnu", "kontingenčnú"],
    "A",
    "V materiáloch je kladný Kurt označený ako leptokurtická distribúcia.",
  ),
  q(
    "uni-12",
    "univariacna",
    "6. Univariačná analýza",
    "Pri kategórii C oproti kategórii B pridávame najmä:",
    ["priemer a štandardnú odchýlku", "iba modus", "Cramerovo V", "reverzné rekódovanie"],
    "A",
    "Kategória C obsahuje kardinálne gaussovské premenné, pri ktorých používame priemer a SD.",
  ),
  q(
    "uni-13",
    "univariacna",
    "06 Univariačná analýza (Word poznámky)",
    "Ak chceme generovať výstupy osobitne pre mužov a ženy, v PSPP použijeme:",
    ["Rank Cases podľa veku", "Compute pre pohlavie", "Reliability", "Split File podľa premennej pohlavie"],
    "D",
    "Split File rozdelí nasledujúce výstupy podľa zvolenej skupinovej premennej; po úlohe ho treba vypnúť.",
  ),
  q(
    "uni-14",
    "univariacna",
    "06 Univariačná analýza (Word poznámky)",
    "V tabuľke početností hľadáme odpoveď na otázku „koľko percent získalo túto alebo nižšiu hodnotu?“ v stĺpci:",
    ["Cum Percent", "Frequency", "Missing", "Mean"],
    "A",
    "Kumulatívne percentá postupne sčítavajú percentuálne zastúpenia až po danú hodnotu.",
  ),
  q(
    "uni-15",
    "univariacna",
    "06 Univariačná analýza (Word poznámky)",
    "Dve skupiny môžu mať rovnaký priemer, no odlišovať sa tým, ako rozptýlené sú hodnoty okolo priemeru. Tento rozdiel vyjadruje najmä:",
    ["modus", "label hodnoty", "štandardná odchýlka", "Cramerovo V"],
    "C",
    "Štandardná odchýlka dopĺňa priemer informáciou o variabilite hodnôt.",
  ),
  q(
    "rel-01",
    "reliabilita",
    "7. Reliabilita psychologického merania",
    "Vzťah X = T + e znamená, že namerané skóre pozostáva zo:",
    [
      "skutočného a chybového skóre",
      "priemeru a mediánu",
      "percent a početností",
      "korelácie a kauzality",
    ],
    "A",
    "Hrubé skóre X je kombináciou pravého skóre T a chyby e.",
  ),
  q(
    "rel-02",
    "reliabilita",
    "7. Reliabilita psychologického merania",
    "Reliabilita psychologického merania vyjadruje:",
    [
      "relatívnu neprítomnosť chýb v meraní",
      "to, že test meria presne požadovaný konštrukt",
      "príčinnú súvislosť premenných",
      "percento žien vo výbere",
    ],
    "A",
    "Reliabilita je spoľahlivosť; validita je odlišná otázka toho, čo test meria.",
  ),
  q(
    "rel-03",
    "reliabilita",
    "7. Reliabilita psychologického merania",
    "Test-retest reliabilitu v PSPP odhadujeme pomocou:",
    [
      "korelácie prvého a druhého merania tých istých ľudí",
      "koláčového grafu pohlavia",
      "rozdielu troch skupín",
      "iba modusu",
    ],
    "A",
    "Pri stabilnej vlastnosti očakávame silný vzťah medzi dvomi meraniami v čase.",
  ),
  q(
    "rel-04",
    "reliabilita",
    "Príkladový test + 7. Reliabilita",
    "Ktoré tvrdenie o odhade reliability metódou split half je pravdivé?",
    [
      "Odhad spočíva vo vytvorení paralelných foriem testu.",
      "Používa iba korelácie medzi jednotlivými položkami bez rozdelenia testu.",
      "Je vhodný iba pre výkonové testy s narastajúcou obťažnosťou.",
      "Je vždy najpresnejším spôsobom odhadu reliability.",
    ],
    "A",
    "Dve formy majú merať rovnakú vec a ich výsledky sa následne korelujú.",
    true,
  ),
  q(
    "rel-05",
    "reliabilita",
    "Príkladový test + 7. Reliabilita",
    "Ktoré tvrdenie o odhade reliability na základe vnútornej konzistencie je nepravdivé?",
    [
      "Podstatou je súvis položiek jednej subškály.",
      "Žiaduca hodnota Cronbachovho koeficientu je blízko k -1 alebo 1.",
      "Vzťahy medzi položkami by mali byť minimálne stredne silné.",
      "Reverzné položky treba pred analýzou správne rekódovať.",
    ],
    "B",
    "Cronbachovo alfa má byť ideálne vyššie ako 0,7; záporná hodnota nie je žiaducim cieľom.",
    true,
  ),
  q(
    "rel-06",
    "reliabilita",
    "7. Reliabilita psychologického merania",
    "Ukazovateľom vnútornej konzistencie dotazníka je:",
    ["Cronbachovo alfa", "Cramerovo V", "Fisherov F-test", "IQR"],
    "A",
    "Cronbachov koeficient α hodnotí konzistenciu položiek jednej dimenzie.",
  ),
  q(
    "rel-07",
    "reliabilita",
    "7. Reliabilita psychologického merania",
    "Ak hodnotenie prejavov optimizmu v príbehoch robí päť hodnotiteľov, zisťujeme reliabilitu ako:",
    ["zhodu posudzovateľov", "test-retest", "súčinovú koreláciu", "výberovú chybu"],
    "A",
    "Pri kódovaní pozorovaní viacerými ľuďmi nás zaujíma miera ich zhody.",
  ),
  q(
    "rel-08",
    "reliabilita",
    "09 Reliabilita (Word poznámky)",
    "Efekt nácviku pri opakovanom pamäťovom teste môžeme pri odhade reliability obmedziť najmä použitím:",
    ["frekvenčnej tabuľky", "paralelných foriem testu", "kontingenčnej tabuľky", "kvótneho výberu"],
    "B",
    "Paralelné formy merajú ten istý atribút rovnakým spôsobom, ale obmieňajú podnetový materiál.",
  ),
  q(
    "rel-09",
    "reliabilita",
    "09 Reliabilita (Word poznámky)",
    "Stĺpec Corrected Item-Total Correlation vo výstupe reliability informuje o:",
    [
      "porovnaní dvoch nezávislých skupín",
      "počte chýbajúcich prípadov",
      "úrovni merania premennej",
      "korelácii konkrétnej položky so zvyškom položiek škály",
    ],
    "D",
    "Položka jednej subškály by mala so zvyškom položiek korelovať kladne a dostatočne silno.",
  ),
  q(
    "rel-10",
    "reliabilita",
    "09 Reliabilita (Word poznámky)",
    "Ak sa Cronbachovo alfa po odstránení určitej položky výrazne zvýši, naznačuje to, že položka:",
    [
      "automaticky dokazuje validitu škály",
      "musí byť vždy zachovaná",
      "môže byť pre vnútornú konzistenciu škály problematická",
      "mení výber na reprezentatívny",
    ],
    "C",
    "Výstup Alpha If Item Deleted pomáha nájsť položky, ktoré znižujú konzistenciu škály.",
  ),
  q(
    "kor-01",
    "korelacny",
    "8. Korelačný psychologický výskum",
    "Z korelačného výskumu môžeme priamo usudzovať:",
    [
      "na silu vzťahu, nie na príčinnú súvislosť",
      "na príčinu a následok bez experimentu",
      "iba na priemer jednej premennej",
      "iba na reliabilitu testu",
    ],
    "A",
    "Súvislosť dvoch premenných sama osebe nepreukazuje kauzalitu.",
  ),
  q(
    "kor-02",
    "korelacny",
    "Príkladový test + 8. Korelačný výskum",
    "Ak v korelačnom výskume zistím hodnotu p väčšiu ako 0,05, konštatujem, že:",
    [
      "nulovú hypotézu nezamietam",
      "medzi premennými existuje štatisticky významný vzťah",
      "vzťah je významný na druhej hladine významnosti",
      "prijímam alternatívnu hypotézu",
    ],
    "A",
    "Pri p > 0,05 nemáme dostatok dôvodov zamietnuť nulovú hypotézu.",
    true,
  ),
  q(
    "kor-03",
    "korelacny",
    "8. Korelačný psychologický výskum",
    "Ak v korelačnom výskume zistíme p < 0,05, potom:",
    [
      "zamietame nulovú hypotézu a konštatujeme štatisticky významný vzťah",
      "nulovú hypotézu nezamietame",
      "vzťah automaticky označíme za kauzálny",
      "nemôžeme výsledok interpretovať",
    ],
    "A",
    "p hodnotí štatistickú významnosť, nie kauzalitu ani silu vzťahu.",
  ),
  q(
    "kor-04",
    "korelacny",
    "Príkladový test + 8. Korelačný výskum",
    "Vzťah medzi dvomi premennými s normálnou distribúciou (typ úlohy CC) nazveme:",
    ["súčinová korelácia", "kontingencia", "poradová korelácia", "modifikovaný korelačný pomer"],
    "A",
    "Pri dvoch kardinálnych gaussovských premenných používame Pearsonov korelačný koeficient.",
    true,
  ),
  q(
    "kor-05",
    "korelacny",
    "Príkladový test + 8. Korelačný výskum",
    "Ukazovateľom sily kontingencie je:",
    ["koeficient eta", "Cronbachovo alfa", "koeficient Cramerovo V", "Pearsonov korelačný koeficient"],
    "C",
    "Kontingencia sa používa pre dvojicu premenných kategórie A a jej silu vyjadruje Cramerovo V.",
    true,
  ),
  q(
    "kor-06",
    "korelacny",
    "Príkladový test + 8. Korelačný výskum",
    "Hodnoty koeficientu Cramerovo V:",
    [
      "sú neohraničené",
      "vyjadrujú silu vzťahu medzi nominálnymi premennými a sú od 0 do 1",
      "pochádzajú z intervalu -1 až 1",
      "udávajú smer priamej alebo nepriamej úmery",
    ],
    "B",
    "Cramerovo V nemá znamienko smeru a nadobúda hodnoty 0 až 1.",
    true,
  ),
  q(
    "kor-07",
    "korelacny",
    "Príkladový test + 8. Korelačný výskum",
    "Druhostupňová tabuľka percent, ktorá „kríži“ dve premenné, sa nazýva:",
    ["korelačná", "kontingenčná", "frekvenčná", "primárna"],
    "B",
    "Kontingenčná tabuľka napríklad kríži ročník a partnerský stav.",
    true,
  ),
  q(
    "kor-08",
    "korelacny",
    "Príkladový test + 8. Korelačný výskum",
    "Koeficient súčinovej korelácie r = 0,6 interpretujeme ako:",
    ["vzťah priamej úmery bez údaja o sile", "chaotický vzťah", "silný pozitívny vzťah", "slabší vzťah ako r = -0,8"],
    "C",
    "Absolútna hodnota od 0,5 sa v materiáloch interpretuje ako silný vzťah; znamienko je kladné.",
    true,
  ),
  q(
    "kor-09",
    "korelacny",
    "Príkladový test + 8. Korelačný výskum",
    "Koeficient súčinovej korelácie r = -0,6 interpretujeme ako:",
    ["vzťah priamej úmery", "žiadny vzťah", "silný negatívny vzťah", "slabý pozitívny vzťah"],
    "C",
    "Absolútna hodnota vyjadruje silu a záporné znamienko nepriamy smer vzťahu.",
    true,
  ),
  q(
    "kor-10",
    "korelacny",
    "Príkladový test + 8. Korelačný výskum",
    "Vzťah medzi dvomi premennými môžeme graficky znázorniť prostredníctvom grafu:",
    ["pie chart", "scatter-plot", "polygon", "histogram"],
    "B",
    "Bodový graf (scatter plot) zobrazuje dvojice hodnôt dvoch premenných.",
    true,
  ),
  q(
    "kor-11",
    "korelacny",
    "8. Korelačný psychologický výskum",
    "Ak Pearsonovo r = 0,5, koeficient determinácie vysvetľuje:",
    ["5 % variability", "25 % variability", "50 % variability", "75 % variability"],
    "B",
    "r² = 0,25 a po vynásobení stomi ide o 25 % variability.",
  ),
  q(
    "kor-12",
    "korelacny",
    "8. Korelačný psychologický výskum",
    "Pri dvoch kardinálnych premenných, z ktorých aspoň jedna je negaussovská, používame:",
    ["Spearmanov koeficient po rankovaní", "Cramerovo V", "Cronbachovo alfa", "Studentov t-test"],
    "A",
    "Úloha BB/BC je poradová korelácia a vyžaduje rankovanie príslušnej premennej.",
  ),
  q(
    "kor-13",
    "korelacny",
    "8. Korelačný psychologický výskum",
    "Pre vzťah premennej kategórie A a kardinálnej gaussovskej premennej C používame:",
    ["koeficient eta", "Spearmanovo rs", "Cramerovo V", "Cronbachovo alfa"],
    "A",
    "Úloha AC sa označuje ako korelačný pomer a ukazovateľom je η.",
  ),
  q(
    "kor-14",
    "korelacny",
    "Príkladový test + 8. Korelačný výskum",
    "Ukazovateľom sily vzťahu medzi kategorizovanou premennou A a kvantitatívnou negaussovskou premennou B je:",
    ["modifikovaný koeficient eta", "koeficient beta", "koeficient determinácie", "koeficient kontingencie"],
    "A",
    "Pri úlohe AB rankujeme premennú B a počítame modifikovaný korelačný pomer ηmod.",
    true,
  ),
  q(
    "kor-15",
    "korelacny",
    "07 Korelačný výskum (Word poznámky)",
    "Pri kontingencii dvoch kategorizovaných premenných zisťujeme štatistickú významnosť vzťahu pomocou:",
    ["chí-kvadrát testu", "Cronbachovho alfa", "medzikvartilového rozpätia", "Leveneho testu"],
    "A",
    "Cramerovo V vyjadruje silu kontingencie, kým chí-kvadrát test sa používa na jej štatistickú významnosť.",
  ),
  q(
    "kor-16",
    "korelacny",
    "07 Korelačný výskum (Word poznámky)",
    "V kontingenčnej tabuľke predstavujú očakávané početnosti (Expected) počty, ktoré by nastali:",
    [
      "ak by bol vzťah maximálne silný",
      "ak by analyzované premenné boli nezávislé",
      "iba po odstránení chýbajúcich hodnôt",
      "ak by Cronbachovo alfa bolo vyššie ako 0,7",
    ],
    "B",
    "Očakávané početnosti sú teoretické počty pri nezávislosti premenných a porovnávajú sa s pozorovanými.",
  ),
  q(
    "kom-01",
    "komparacny",
    "9. Komparačný psychologický výskum",
    "Komparačný psychologický výskum sa primárne zaujíma o:",
    ["rozdiel medzi minimálne dvomi objektmi", "kauzalitu bez experimentu", "iba jednu premennú bez skupín", "kódovanie labelov"],
    "A",
    "V komparačnom výskume porovnávame úroveň alebo distribúciu medzi skupinami.",
  ),
  q(
    "kom-02",
    "komparacny",
    "Príkladový test + 9. Komparačný výskum",
    "Alternatívna hypotéza v komparačnom výskume je tvrdenie, ktoré:",
    [
      "predpokladá, že medzi skúmanými populáciami existuje rozdiel",
      "považujeme za pravdivé, pokiaľ nemáme dôvody pre opak",
      "predpokladá, že medzi populáciami neexistuje vzťah",
      "zamietame, ak p < 0,05",
    ],
    "A",
    "Alternatívna hypotéza hovorí, že sa niečo deje, teda že rozdiel existuje.",
    true,
  ),
  q(
    "kom-03",
    "komparacny",
    "Príkladový test + 9. Komparačný výskum",
    "Vecná významnosť v komparačnom výskume:",
    [
      "môže byť vyjadrená korelačnou mierou veľkosti rozdielu",
      "určuje iba to, či je p menšie ako 0,05",
      "je totožná s nulovou hypotézou",
      "označuje možnosť zovšeobecnenia na populáciu",
    ],
    "A",
    "Vecná významnosť vyjadruje praktickú veľkosť rozdielu, teda effect size.",
    true,
  ),
  q(
    "kom-04",
    "komparacny",
    "9. Komparačný psychologický výskum",
    "Ak pri porovnaní skupín platí p <= 0,05, potom:",
    [
      "nulovú hypotézu zamietame",
      "nulovú hypotézu vždy prijímame",
      "rozdiel je určite veľký",
      "výskum sa mení na korelačný",
    ],
    "A",
    "Štatistická významnosť hovorí o existencii rozdielu, nie automaticky o jeho veľkosti.",
  ),
  q(
    "kom-05",
    "komparacny",
    "9. Komparačný psychologický výskum",
    "Porovnávame dve nezávislé skupiny a závislá premenná je gaussovská. Použijeme:",
    ["Studentov t-test", "Mannov-Whitneyho U test", "Kruskalov-Wallisov test", "Cramerovo V"],
    "A",
    "Pre dve nezávislé skupiny s gaussovskou závislou premennou materiály uvádzajú t-test.",
  ),
  q(
    "kom-06",
    "komparacny",
    "9. Komparačný psychologický výskum",
    "Porovnávame dve nezávislé skupiny a závislá premenná je negaussovská. Použijeme:",
    ["Studentov t-test", "Mannov-Whitneyho U test", "Fisherov F-test", "Cronbachovo alfa"],
    "B",
    "Pri negaussovskej premennej sa pracuje s poradím a Mannovým-Whitneyho U testom.",
  ),
  q(
    "kom-07",
    "komparacny",
    "Príkladový test + 9. Komparačný výskum",
    "Porovnávame gaussovsky distribuovanú premennú v troch nezávislých skupinách. Vhodný test je:",
    ["Studentov t-test", "Fisherov F-test (jednoduchá ANOVA)", "Mannov-Whitneyho U test", "Cramerovo V"],
    "B",
    "Pri troch a viacerých skupinách a gaussovskej premennej používame Fisherov F-test.",
    true,
  ),
  q(
    "kom-08",
    "komparacny",
    "9. Komparačný psychologický výskum",
    "Pri troch a viacerých skupinách a negaussovskej závislej premennej materiály uvádzajú:",
    ["Kruskalov-Wallisov test", "Studentov t-test", "Cronbachovo alfa", "kontingenčnú tabuľku"],
    "A",
    "Kruskalov-Wallisov test je viacvýberový neparametrický postup.",
  ),
  q(
    "kom-09",
    "komparacny",
    "9. Komparačný psychologický výskum",
    "Párový test je potrebný vtedy, keď:",
    [
      "meriame tú istú skupinu participantov pred a po kurze",
      "porovnávame Slovákov a Španielov z odlišných výberov",
      "máme dve nominálne premenné",
      "vytvárame názov premennej v PSPP",
    ],
    "A",
    "Opakované merania v rovnakom výbere sú závislé, teda párové.",
  ),
  q(
    "kom-10",
    "komparacny",
    "9. Komparačný psychologický výskum",
    "Leveneho test pri Studentovom t-teste zisťuje:",
    ["rovnosť variancií skupín", "vnútornú konzistenciu", "normalitu názvu premennej", "silu kontingencie"],
    "A",
    "Výsledok Leveneho testu určuje, ktorý riadok t-testového výstupu interpretujeme.",
  ),
  q(
    "kom-11",
    "komparacny",
    "08 Komparačný výskum (Word poznámky)",
    "Chyby I. typu sa dopustíme, keď:",
    [
      "nezamietneme pravdivú nulovú hypotézu",
      "zamietneme nepravdivú nulovú hypotézu",
      "vypočítame štandardnú odchýlku",
      "zamietneme pravdivú nulovú hypotézu",
    ],
    "D",
    "Chyba I. typu, označovaná α, znamená zamietnutie H0, hoci H0 v skutočnosti platí.",
  ),
  q(
    "kom-12",
    "komparacny",
    "08 Komparačný výskum (Word poznámky)",
    "Podľa poznámok pri porovnaní dvoch nezávislých skupín s negaussovskou premennou v staršom PSPP bez priameho Mannovho-Whitneyho U testu postupujeme tak, že:",
    [
      "vypočítame iba Cronbachovo alfa",
      "premennú označíme ako Missing",
      "premennú zrankujeme a aplikujeme t-test na ranky",
      "použijeme výlučne koláčový graf",
    ],
    "C",
    "Word poznámky uvádzajú rankovanie a t-test s rankami ako praktický postup pre túto verziu PSPP.",
  ),
  q(
    "kom-13",
    "komparacny",
    "08 Komparačný výskum (Word poznámky)",
    "Jednostrannú alternatívnu hypotézu volíme vtedy, keď:",
    [
      "predpovedáme aj smer rozdielu, napríklad že výkon sa zvýši",
      "nepredpovedáme žiadny rozdiel",
      "zaujíma nás výlučne reliabilita",
      "pracujeme iba s nominálnymi labelmi",
    ],
    "A",
    "Jednostranná hypotéza špecifikuje smer očakávaného účinku; dvojstranná predpokladá rozdiel bez určenia smeru.",
  ),
];

export const exampleTestQuestionCount = psychologyQuestions.filter((question) => question.fromExampleTest).length;
